sqm-autorate.sh

Instead of duplicating the logic for ul and dl just create a helper function
and feed it with the relevant parameters for dl or ul.
This also reduces the use of global variables to make it easier
to treat dl and ul separately.

Use one parameterized function for selecting the next rate

---

sqm-autorate.sh

This tail call is unnecessary if using the most recent version of hping_parser.awk.

Removed unnecessary tail call.

---

CAKE-autorate.sh

Older iputils ping returns:
root@turris:~/CAKE-autorate# ping -c 1 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_req=1 ttl=58 time=9.66 ms
--- 1.1.1.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 9.666/9.666/9.666/0.000 ms
while more modern png returns:
user@work-horse:~/CODE/OpenWrtScripts$ ping -c 1 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=57 time=9.93 ms
--- 1.1.1.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 9.929/9.929/9.929/0.000 ms
so icmp_req was changed into icmp_seq. To allow both versions of ping
make the parser indifferent to "s" and "r" in icmp_?eq.
Signed-off-by: Sebastian …

Allow for older iputils ping

---

fn_parse_autorate_log.m

Fixed version of the plotting helper:
The following invocation will work non-interactively:
`octave -qf --eval 'fn_parse_autorate_log("./SCRATCH/cake-autorate.log.20221001_1724_RRUL_fast.com.log", "./out.png")'`
First argument is the input log file, the second optional argument is the outputfile, the file type is detected from the extension, `.png` in the example, known types are:
```
.pdf
.png
.tif
.ps
```
BTW: Sorry for the lost PR, I had srewed up my local git repository and in the course of fixing that I deleted the old branch and had to re-create it.

Octave plotter

---

fn_parse_autorate_log.m

This avoids plotting nothing if the data has fewer samples then expected.

Change default x_range to all samples in the log

---

fn_parse_autorate_log.m

This accidentally searched in an X by Y array instead of the 1 by Y slice of the array an the resulting linear array hence was not the correct index of the Y-position.

Fix the quantile reporting for unloaded latency.

---

fn_parse_autorate_log.m

This also revealed a yet untriggered bug in the generalized header parsing function that got fixed en passant.
Took some git iteration to get rid of the changes to cake-autorate.sh that I accidentally included in the first try...

Add REFLECTOR and REFLECTOR_HEADER record types to parser

---

cake-autorate.sh

The parser was unhappy about a missing ";".

Add missing semi-colon in LOG_HEADER

---

cake-autorate.sh
cake-autorate_launcher.sh

So this is the version I am currently testing (I made some changes today so this needs a bit more baking).
Note I upped the verbosity of the launcher and switched to one-by-one termination (required for better verbosity).
While I consider your ERROR logging approach both elegant and opaque, I think the cmd_wrapper approach is more appropriate as for debugging I want to see both failure and success reports. Note how SILENCE_CMD can be used to toggle cmd_wrapper to demote expected errors to debug messages instead, still even when expected logging them seems helpful.
This is mainly intended to give you visibility on the "hack and slash" I submitted your code to, sorry ;)
This time I hope I got the intended branch....

Testing mod 20221220

---

cake-autorate_launcher.sh

If multiple cake-autorate instances are used it helps to have some information about them starting and stopping.
So add this to the system log. Note this switches from bulk killing all instances to killing them on-by-one to disentangle their termination processes from each oher to some degree.

Change the launcher to report start and termination per instance

---

cake-autorate.sh
cake-autorate_config.primary.sh

The new config file parameter log_DEBUG_messages_to_syslog allows to steer a copy of all DEBUG records (in addition to all ERROR records that by default are added to the log) into the system log file to ad in debugging. Note this can be a fire hose of entries so this should default to off (0)

Allow logging all DEBUG records to the system log

---

cake-autorate.sh

Messages look like:
Jan  8 11:54:21 turris cake-autorate.vdsl2: DEBUG: 1673178861.364126 maintain_pingers: Starting up...
instead of the previous:
Jan  8 11:54:21 turris cake-autorate: DEBUG: 1673178861.364126 maintain_pingers: Starting up...
this way system log messages for concurrent instances can be disambiguated.

Add the instance ID to the syslog type argument

---

cake-autorate.sh

…to improve the log type tag
Placed at the current position before ${instance_id} is initiated the SYSLOG message looked like:
Jan 20 19:59:25 turris cake-autorate.: SYSLOG: 1674244765.530486 Starting cake-autorate with config: /root/cake-autorate/cake-autorate_config.vdsl2.sh
missing the ${instance_id} as suffix after autorate to disambiguate different instances with this commit this message now looks like expected:
Jan 20 20:01:53 turris cake-autorate.vdsl2: SYSLOG: 1674244913.515046 Starting cake-autorate with config: /root/cake-autorate/cake-autorate_config.vdsl2.sh

Syslog move start meassge after instance_id instantiation

---

cake-autorate-setup.sh
cake-autorate.sh
cake-autorate_launcher.sh
lib.sh

* `${reflectors[@]:0:${no_pingers}}` without quotes has the risk of
being expanded improperly if an array element contains spaces
(never going to happen but it doesn't hurt to put it in quotes)
* dl_delays and ul_delays are initialized improperly, at startup
they only have one element because `for i in {1..${bufferbloat_detection_window}};`
doesn't get expanded into `for i in {1..<some num here>}`..
(limitation of brace expressions)

Replace FIFOs with file descriptors and other improvements and fixes

---

cake-autorate_setup.sh

* No need for blanket chmod +x
* Install service to /etc/init.d
* Set tar -o option to ensure user info is not restored (GitHub thankfully sets root, but better be safe than sorry)

Some fixes for the setup script

---

TODO.txt
fn_parse_autorate_log.m

Fixes a regression in te plotting scripts handling of LOAD records in the absence of DATA record entries.
Should fix:
https://forum.openwrt.org/t/cake-w-adaptive-bandwidth/135379/2276

Plot pure load data fix

---

cake-autorate.sh

* If value is empty, we will think the number is 0. This fixes the issue.

Fix bug introduced by 17607d7e90e2cd68b1f3fe214b9561a760a255bb

---

cake-autorate_setup.sh

* Seeing that even developers make this error, it seems wise to protect users from themselves.

Add safety check to avoid bug reports caused by updating while running

---

ANALYSIS.md
CHANGELOG.md
INSTALLATION.md
README.md

With the impending release of a new version (after my test with an Archer c7), I decided to take a crack at the documentation.
I factored the main README into three files:
- README with introductory material
- INSTALLATION describing how to install on OpenWrt
- ANALYSIS discussing how to analyze log files
I also took the liberty of updating the CHANGELOG file to version 2.1, and reviewed the commit history to collected a few notes.
What's new in this PR:
- I made an editorial pass over all the files, using my best judgement to fix typos, and (hopefully) clarify descriptions
- I used `markdownlint` to check the Markdown file formats. This results in much shorter lines that will make subsequent edits more clear. It also fixes up some problems with the original Markdown markup.
- There's no …

docs: Factor README

---

ANALYSIS.md
CHANGELOG.md
INSTALLATION.md
LICENCE.md
README.md

Add a wrap limit of 70 to all markdown documents to make reading
and more importantly editing/general maintainance (like comparing
diffs) easier.
This commit was generated using `mdformat --wrap 70 .`

Format all markdown documents

---

cake-autorate.sh

"Improve log file descriptor flush" dropped the -r switch from the read command.

Use read -r in newly introduced code

---

cake-autorate.sh

Using "mwan3 use X ..." for tsping does not work properly due to the developers calling "..." using $*. This works around the issue by using `,` as the delimiter instead.
Fixes #246

Use comma as delimiter for tsping

---

cake-autorate.sh

Reduce nesting and slight fix of inconsistent tabs/space which
need some work to be fully "fixed."
While cleaning up, a bug was found where the iputils-ping parser
was checking if ts == cksum but not skipping the loop if it were
the case. This was addressed along with the general cleanup.

Cleanup and fix bug in parser for iputils-ping

---

cake-autorate.sh

When startup_wait_s is non-zero, anything dependent upon initial timestamps (e.g., the reflector timeout period) will be affected by the sleep. If the reflector timeout period is less than the startup_wait_s duration. this causes a fatal crash immediately after the startup sleep ends.
This is addressed by sleeping before assigning any initial timestamps.

fix: Delay startup before assigning initial timestamps

---

Example_Starlink_config.sh
cake-autorate
cake-autorate.sh
config.primary.sh
defaults.sh
launcher.sh
lib.sh
maint/update_setupsh_branch.sh
maint/version_bump.sh

Use /usr/bin/env everywhere when spawning bash

---

INSTALLATION.md
cake-autorate.sh
config.primary.sh
defaults.sh

The default idle threshold of 1MBit/s seems to be too low for a typical set of home IoT devices, resulting in the sleep activation logic never triggering  - see [here](https://forum.openwrt.org/t/cake-w-adaptive-bandwidth/135379/3507). In any case, it seems apt to add this as one of the configuration options present in config.primary.sh.
And the term 'instance' is more appropriate than 'interface' in respect of config.x.sh.

Increase idle thr & improve config documentation

---

fn_parse_autorate_log.m

On encountering an incomplete line, stop parsing, and work with the complete records parsed so far.

Gracefully deal with incomplete lines in the logfile

---

ANALYSIS.md

With the latest OpenSSH version, scp is now just a wrapper to sftp. The issue with that is that the sftp binaries are not present in OpenWRT by default. As a solution, we specify `-O` which allows us to use the the actual SCP protocol.

Update "scp" command for latest OpenSSH version

---

fn_parse_autorate_log.m

Teach the parser to skip over lines not containing the expected number of fields.
Also add the SUMMARY record type to the parser to clean up the output.
As it says on the tin, make it more robust and less verbose... Currently SUMMARY records are fully parsed, but not used any further...

Robustify the log parser and add the SUMMARY record type

---

ANALYSIS.md
fn_parse_autorate_log.m

From @moeller0:
The issue is that recent Octave/Ghostscript combinations crash while trying to export the timecourse plot. The PNG exporter however does seem to work.
-------------------
I also made some miscellaneous changes to the Octave script like having it use CRLF endings consistently and fixed an trivial formatting issue in initialization section of log_struct.

Update ANALYSIS.md export instructions to use PNG not PDF

---

.gitignore
fn_parse_autorate_log.m
maint/octave_formatter.py

Modified from matlab-formatter-vscode to add GNU Octave support and to adapt
it to cake-autorate's needs (i.e., I added some features like inplace, tabs,
argparse, etc.).
Further, I fixed in which a line like:
`if ...'LOAD', 'REFLECTOR'}) % {'DEBUG', 'INFO', 'SJHAPER'}` would break the
formatter in addition to other more subtle issues.
It is based on https://github.com/affenwiesel/matlab-formatter-vscode commit 43d7224.
For reference on what needs to be modified, see
https://en.wikibooks.org/wiki/MATLAB_Programming/Differences_between_Octave_and_MATLAB
In some parts of the script, there is some usage of `end`.
It doesn't really matter but I prefer for the script to be
more consistent.

Add an Octave formatter and make our script compliant with formatter

---

fn_parse_autorate_log.m

Matlab only accepts a generic "end" while octave allows to document scope better by having distinct end variant like:
if ... endif
for ... endfor
While the code originally started under matlab, by now it is essentially octave only anyway so convert the last unadorned ends...

Fully commit on octave-first and octave-only for end statements

---

cake-autorate.sh
lib.sh

The below changes reduces CPU usage by 0.5% on my X86 machine:
- Switch to using `:` instead of `true` as it is consistently faster in the below benchmark, unsure why as they are both noops:
+ timeout 3 bash -c 'while :; do true; echo y; done'
+ wc -l 1881683
+ timeout 3 bash -c 'while :; do :; echo y; done'
+ wc -l 2152695
- Switch to switch case for the idle/sleep function handling code.
- Remove unneded non-empty string handling check

Some more bash optimizations

---

cake-autorate.sh
cake-autorate.template
config.primary.sh
launcher.sh.template
maint/version_bump.sh
setup.sh
uninstall.sh

This allows the user to override the default /root/cake-autorate path and should clear the path for a more standard installation.

Add ASUSWrt-Merlin support and don't hardcode /root/cake-autorate

---

INSTALLATION.md
README.md
setup.sh

@LiveWire1968 any chance you could test the latest code on this asus-merlin branch and we'll add any necessary remaining fixes?
I think(?) the installation instructions should be something like:
Make sure these are installed: entware; bash; iputils-ping; and fping.
And then run:
```
wget https://raw.githubusercontent.com/lynxthecat/cake-autorate/asus-merlin/setup.sh
chmod +x ./setup.sh
./setup.sh lynxthecat/cake-autorate asus-merlin
```
And then edit the config file to specify the correct interfaces:
```
dl_if=ifb4eth0 # download interface
ul_if=eth0     # upload interface
```
and bandwidths (change according to your connection specifics):
```
min_dl_shaper_rate_kbps=5000   # minimum bandwidth for download (Kbit/s)
base_dl_shaper_rate_kbps=60000 # steady state bandwidth for download …
```

Add remaining Asus Merlin fixes to installer

---

CHANGELOG.md
INSTALLATION.md
cake-autorate.sh
defaults.sh

Improve controller by easing off on the rate of shaper rate increase as the average OWD delay crosses a new threshold and approaches the delta delay threshold

Scale rate increases as OWDs near delay threshold

---

INSTALLATION.md

Experimental SNAPSHOT builds switched USE_APK to y recently.
Fixes: https://github.com/lynxthecat/cake-autorate/issues/317

Mention that apk may be required if opkg is not found

---

README.md

You should check the changes carefully. 
* Tweak lead paragraph to emphasize that "cake-autorate minimizes latency in routers..."
* Adjusted description of the algorithm to emphasize ramping up to maximum, then decreasing in the face of latency. The low-traffic scenario is less important to people's understanding.
* Check the final point - is the "refractory period" description correct? And does it tend to adjust in well under one second?
Thanks!

Tweak README to clarify algorithm and lead paragraph
