lynxthecat/cake-autorate

sqm-autorate.sh
Reverts lynxthecat/sqm-autorate#1
=> Revert @moeller0's changes given issue with 'local' variables

sqm-autorate.sh
I figured out the solution to the problem.
=> Revert "Revert @moeller0's changes given issue with 'local' variables"

sqm-autorate.sh
let's avoid bc in openwrt and use awk everywhere
=> Replace bc with awk

README.md
Minor edits to the explanations. Please make sure I haven't said anything that's untrue. Thanks.
=> Editorial pass over the README

cake-autorate-setup.sh
=> Fix errors in setup script

fn_parse_autorate_log.m
Exclude sequence 0 RTT samples as these have an artificially high baseline.
Also allow to directly operate on gzipped log files.
=> Parser improvements

fn_parse_autorate_log.m
also add "*.log.old" and "*.log.old.gz" to the file loading dialog wildcards.
Convenience fixes...
=> Make the parser skip but report unknown record type identifiers

fn_parse_autorate_log.m
The commit also contains a number of other small improvements.
=> Switched the main fuction to try catch to get better error reporting.

fn_parse_autorate_log.m
This should allow scaling of the delay y-axis based on the maximum of the adjusted thresholds (via a factor) as well as a quantile and a factor of the OWD deltas. Seems to work fine.
This also plots the Delay on the first/left axis, resulting in the rate lines ending up on top.
=> Plotting improvements delay scaling

fn_parse_autorate_log.m
The new LOAD records contain the achieved rates from the rate sampling process these mostly are redundant with the achieved rate fields in the DATA records except LOAD records are also written during sleep. This allows to confirm whether exit from sleep happens at the desired load thresholds as well as logging the variable load during sleep.
Mind you, the actual plotting part still ignores the new data, this is only about parsing the data without erroring out. The code should still work for older log files...
=> Add the LOAD_HEADER and LOAD record types to the parser

fn_parse_autorate_log.m
This will now plot achieved rates during sleep periods which might help to confirm wake from sleep happens under the expected/configured conditions. This also fixes small issues (like actually reading in the LOAD records instead of just silently ignoring them).
This also switches the range definition from sample indices to time in second. Since log file start as DATA and LOAD data have independent time axis, there is no guaranteed common time index. Also time based ranges are more intuitive. The code will select the next best sample for each end of the range so specification does not need to be overloy precise. This range can now be specified when calling from
the command line as optional 3rd argument.
=> Switch plotting of achieved rates from DATA to LOAD record information

fn_parse_autorate_log.m
Try to plot something interesting in regards to high and ow load conditions.
=> Plot cd fs by load percentage

fn_parse_autorate_log.m
This seems to work for fping data, but probably needs fixing with real OWD data.
This also fixes the mis-spelling of cumulative as cummulative on the y-axes... spelling is not my forte, nor is typing ;)
=> Add a plot of RTT CDFs to the CDF plot

fn_parse_autorate_log.m
This fixes the outstanding bug with SHAPER records that caused unhandled exceptions before and cleans up the CDF plots. It also adds a plot of the daltaCDFs to the existing rawCDF plot.
=> More plotting fixes

fn_parse_autorate_log.m
=> Allow reflectors with no data for CDFs

fn_parse_autorate_log.m
This allows to request plotting only for a subset of reflectors.
=> Plotting changes 02

fn_parse_autorate_log.m
=> Plotting changes 04

fn_parse_autorate_log.m
In addition ot CDFs this allows to also plot PDF/histograms of the delay distributions. However at least for the flent delay source the time quantisation requires a bin-size of 200µs, and the resulting distributions are really small, so at least for low load these plots are deswkected in te default set.
This also fixes a yet un-triggered bug in the distribution calculation function.
=> Fix plotting of PDFs.

cake-autorate.sh
System logfiles typically cover longer epochs than cake-autorate's own log file, so also add ERROR records to the system log. This seems sane as long as ERROR records are both rare and important for the user to act on.
=> ERRORs are important enough to also log into the system log file

CHANGELOG.md
This can describe new work that might be available in the current code, but hasn't seen a full release.
Having the **Unreleased** section allows you to write up the features as they're being checked in, so it's not such a scramble when it's time for a real release.
Feel free to flesh out my mumblings...
=> Update CHANGELOG.md to have "Unreleased" section

CHANGELOG.md
Reverts lynxthecat/cake-autorate#104
=> Revert "Update CHANGELOG.md to have "Unreleased" section"

cake-autorate.sh
For debugging it is helpful to know when a specific autorate instance was terminated to add a message to the system log.
=> Add stopp message to cleanup_and_killall

fn_parse_autorate_log.m
This reduces the memory demany by increasing the CDF granularity from 1 µsec to 5 µsec and by clearing the large CDF data structures after use. This should make plotting feasible again without excessive memory demands.
=> Reduce the required memory for octave's CDF/PDF plots

cake-autorate.sh
Fixes https://github.com/lynxthecat/cake-autorate/issues/120
=>  Set trap to true while in the process of gracefully shutting down 

cake-autorate.sh
I wasn't able to trigger the issue but I'm struggling to do so even with the current testing branch (even though I should be able to); so I'm kind of trying to fix the issue even though I don't experience. Either way hopefully it works!
I reverted https://github.com/lynxthecat/cake-autorate/commit/8a0e9d3b055a8c2271d5d048ed9e6731c992ede3 because it's too hacky for my liking. I prefer the FIFO approach aesthetics wise. 
Might fix https://github.com/lynxthecat/cake-autorate/issues/120
=> Another attempt at fixing service shutdown issue

cake-autorate-setup.sh
* busybox tar actually has a -z option
=> don't pipe to zcat

cake-autorate.sh
https://forum.openwrt.org/t/cake-w-adaptive-bandwidth/135379/2210?u=rany
=>  Improve "another instance is running check" 

cake-autorate_lib.sh
* This will help in fixing the race condition with fping
=> Add lock and unlock functions in cake-autorate_lib.sh

cake-autorate_launcher.sh
=> Add wait inside trap as well

cake-autorate_lib.sh
=> Fix comment for our own sleep function

cake-autorate_setup.sh
=> Improve cake-autorate_setup script

README.md
=> Spellcheck README.md

setup.sh
=> Add optional argument(s) to setup.sh

Example_Starlink_config.sh, cake-autorate.sh, config.primary.sh, defaults.sh, lib.sh
=> Validate user configuration entries

setup.sh
This makes sure that in the event setup.sh is overwritten, there won't be a situation where sh might fail to read the file or read invalid file contents.
=> Ensure setup.sh code is loaded before executing code

setup.sh, uninstall.sh
When encapsulating I missed this.
=> Pass arguments to main funcs of setup and uninstall

fn_parse_autorate_log.m
Add:
DL_AVG_OWD_DELTA_US;
DL_ADJ_OWD_DELTA_THR_US;
UL_AVG_OWD_DELTA_US;
UL_ADJ_OWD_DELTA_THR_US;
to the delay plots, if those fields exist in the DATA records
This also contains small additional fixes...
=> Add new delay data to the plots.

INSTALLATION.md, maint/mdformat.sh
Addresses issue that caused https://github.com/lynxthecat/cake-autorate/pull/259
=> Mdformat fixes

INSTALLATION.md, setup.sh
=> v3.1 fixes

fn_parse_autorate_log.m
Modern octave prefers a blank '+' over the old '.*' notation, so fix the 3 occurrences ...
Also set the default format to png...
=> Update parse log 4 recent octave

fn_parse_autorate_log.m
Mostly cleanup of indentation and some spelling fixes.
=> Parsing changes 03

setup.sh
=> Self replace setup.sh if it does not match remote

setup.sh
=> Fix typo introduced by PR #299

maint/version_bump.sh
=> Update version branch link in README.md
